### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by wvdongen** [codewatchorg/sqlipy#1]
Great job! 

Here are a few things that could be nice additions I think. Better overview of what scans are running. Show SQLiPY tests in the scan queue of Burp? Currently you would have to go the extender and look at the output to see “Scan for task 9fb2cdda8d37dd3e is still running.”.  I don’t know if this is possible with sqlmapapi, but for a specific SQLiPy scan it would be nice to have some kind of status, what type of injections are currently being tested for example.

**Comment by codewatchorg** [comment]
Fixes made and features added months ago.  Forgot to close this out.
