### ISSUE TITLE
"Start Scan" button in SQLMAP Scanner Tab is not visible

### ISSUE THREAD

**Issue by ishangirdhar** [codewatchorg/sqlipy#10]
Hi Josh,

First of all thank you for writing this awesome burp extension, it comes real handy in identifying parameters vulnerable to sql injection using SQLMap. However, I have been facing this issue where I don't see "Start Scan" button in SQLMAP Scanner Tab. I reached out to Burp Support and they were able to see the "Start Scan" button somehow. 

I have tried the following things:

1. Changing Display UI to Metal, OS x and Nimbus.
2. Using it with updated Oracle Java installed.
3. Using it on Burp pro and Burp Free
4. Using it on Mac OS x and Kali Linux (Both Free and Pro Version)
5. Re-Installing SQLipy Extension
6. Re-installing Jython

but nothing seems to be working, I am using Burp (Paid and Free) and Jython latest version.

There are no errors generated only the following output:

```
Calling: /usr/bin/python /usr/share/sqlmap/sqlmapapi.py -s -H 127.0.0.1 -p 8888

[06:36:49] [INFO] Running REST-JSON API server at '127.0.0.1:8888'..
[06:36:49] [INFO] Admin ID: 683e40ffbf9de08abf671fe0baec0532
[06:36:49] [DEBUG] IPC database: /tmp/sqlmapipc-sHXl8u
[06:36:49] [DEBUG] REST-JSON API server connected to IPC database
```

What do you think could be causing this issue?

Let us know your thoughts on this.

-Ishan

**Comment by codewatchorg** [comment]
What is the resolution of the monitor set to?  What version of the extension are you using?  What version of Jython are you using?  What is the actual full version of Java in use?  Do you see all of the other form fields in the "SQLMap Scanner" tab?  Can you provide a screenshot of what you see on that tab?  Within Burp, in the "User options"->"Display" tab, what is the font size set to?

**Comment by fengdingbo** [comment]
trying find in SQLiPy.py "self._jButtonStartScan.setBounds(346, 1047, 103, 29)"
change "self._jButtonStartScan.setBounds(346, 10, 103, 29)"

**Comment by ishangirdhar** [comment]
Hi @codewatchorg ,

Version Details are follows:

```
Burpv 1.7.0.4
SQLiPy - 0.5.0
Java 8 Update 101
Resolution:	2560 x 1600 Retina
Jython Version: Standalone 2.7.0.jar
```

Burp Diagnostics
```
java.runtime.name                Java(TM) SE Runtime Environment
java.runtime.version             1.8.0_101-b13
java.specification.version       1.8
java.version                     1.8.0_101
java.vm.version                  25.101-b13
os.arch                          x86_64
os.name                          Mac OS X
os.version                       10.11.6
```

Yes I am able to see all other form fields and controls just not **"Start Scan Tab"**.

Font Size is Default: 11 (default)

Screenshot Attached.

<img width="1392" alt="screen shot 2016-08-11 at 3 17 12 pm" src="https://cloud.githubusercontent.com/assets/2884252/17584939/d19ebe6c-5fd6-11e6-8af0-2ea9f1eeb255.png">
<img width="1392" alt="screen shot 2016-08-11 at 3 17 18 pm" src="https://cloud.githubusercontent.com/assets/2884252/17584940/d19f2258-5fd6-11e6-9282-9811fd96040a.png">

**Comment by ishangirdhar** [comment]
@fengdingbo 

Thank you so much, I have change the setBound values as you mentioned and Now I can see the button on the top.

Thank you.

<img width="1392" alt="screen shot 2016-08-11 at 3 21 50 pm" src="https://cloud.githubusercontent.com/assets/2884252/17585069/5ad5c9dc-5fd7-11e6-8b5f-cda36f9e5c31.png">

**Comment by codewatchorg** [comment]
I have updated the code to version 0.5.2, adding a new feature as well as fixing this issue of the start button not displaying.  It is in Github now but hopefully will be added to the BApp store soon.

**Comment by ex0dus-cpp** [comment]
How can i install sqlipy in burp manually from git without bapp store?

**Comment by codewatchorg** [comment]
Dmitry,

 

You just download the script file, then when you start Burp go to the “Extender->Extensions” tab and hit the “Add” button.  In the “Extension Details” you change the type to Python, hit the “Select file” button and navigate to where you downloaded the script, and then click the “Next” button.

 

Thanks,
Josh
