### ISSUE TITLE
Arbitrary injection point on POST data is not working

### ISSUE THREAD

**Issue by riramar** [codewatchorg/sqlipy#12]
If you use injection point (`*` or `%INJECT HERE%`) in a POST Data request with JSON (e.g. `{ "name" : "value*" }`) sqlmap is actually URL encoding the special characters (e.g. %7B%20%22name%22%20%3A%20%22value%22%20%7D) before sending to the server.
I've noticed this problem because I'm intercepting all the sqlmap requests with a proxy.
Without SQLipy extension sqlmap do not perform the URL encoding.

**Comment by codewatchorg** [comment]
This issue isn't quite clear to me.  Does this only occur when using sqlipy?  Are you saying that sqlipy encodes the values that it sends to the sqlmapapi server?  I don’t develop sqlmap itself, just the integration between Burp and sqlmap, so I can only fix issues related directly to sqlipy.

**Comment by riramar** [comment]
I'm not sure exactly which component is performing the URL encoding.
I'm assuming this workflow:

Burp > sqlipy > sqlmapapi > MyProxy > target

Looking to the requests on MyProxy I can see the request JSON payload with the special chars URL encoded.
If I do the exactly same scan but from command line:

Shell > sqlmap > MyProxy > target

From MyProxy in this case the URL encoding is not performed.

**Comment by riramar** [comment]
One more comment, in the workflow below without any injection point (* or %INJECT HERE%) the URL encoding is not performed.

Burp > sqlipy > sqlmapapi > MyProxy > target

**Comment by codewatchorg** [comment]
Hmm, I will look into it.  The sqlmap API server might be encoding the data and then passing it on to sqlmap that way.  I don't believe SQLiPy is encoding anything.

**Comment by riramar** [comment]
I've opened an issue on sqlmap github and it seems to be fixed now. :)

**Comment by stamparm** [comment]
@riramar I've fixed this issue (not related to sqlmap's #2568) here with latest commit (https://github.com/sqlmapproject/sqlmap/commit/7dbbf3ecf5f96ab7c6d77b72d8f4789a037af600)

**Comment by riramar** [comment]
Thanks a lot @stamparm !!!
