### ISSUE TITLE
sqlipy can't parse sqlmapapi response(JSON) correctly.

### ISSUE THREAD

**Issue by ehaoxiongdiycw** [codewatchorg/sqlipy#15]
Hello, 

I use Burp(Version: `1.7.19`) and sqlmap(Version: `1.1.11#stable`) just now, and i use sqlipy to connect them as usual.

But i found that sqlipy can not report SQL Injection Vulnerability as the blog says. So i modify the source code, add some traceback information and re-run, something interesting has been found.

![3](https://user-images.githubusercontent.com/7035940/33420101-4dc8d7e2-d5e8-11e7-92dc-bbf9708fd71f.PNG)

sqlipy raise EXCEPTION when parse sqlmap api resonse JSON data.

I adjustment some parameters in the sqlipy and all thing work well. Just as fllow.

![1](https://user-images.githubusercontent.com/7035940/33420035-028c2aae-d5e8-11e7-9c52-85f682bd8721.PNG)

![2](https://user-images.githubusercontent.com/7035940/33420270-debe1118-d5e8-11e7-847b-6e08816c1c16.PNG)

Maybe sqlmap api response JSON has been changed. So it's better to update sqlipy to follow sqlmap.

**Comment by codewatchorg** [comment]
I just pushed a fix.  It looks like the sqlmap team had changed the values assigned by type (the type went up by 1 for each class of enumerated info).  I will work with the PortSwigger team to get the latest version in the BAPP store.
