### ISSUE TITLE
Improve Python detection

### ISSUE THREAD

**Issue by pajswigger** [codewatchorg/sqlipy#18]
SQLmap uses Python 2, so distributions like Arch that default to Python 3 need to use python2.

On Windows, many users do not add Python to the path, but the location is available in the registry.

If Python 2 is not available, it would be useful to provide the user with a message.

**Comment by codewatchorg** [comment]
I added registry checking logic to find the Python path in commit: https://github.com/codewatchorg/sqlipy/commit/768fb34d4020e1399e74fe122fc69253174dee69

**Comment by codewatchorg** [comment]
Ok, I added a Python version check.  If it doesn't return 2.7, then it will now auto set the Python path and will output an error in the console.  The commit is: https://github.com/codewatchorg/sqlipy/commit/15e85954d6fde6d30936c765199afa3ed5f139fa
