### ISSUE TITLE
Unable to start API

### ISSUE THREAD

**Issue by arkadiyala** [codewatchorg/sqlipy#20]
I have downloaded jython into "C:\jython2.7.0"

I'm unable to start start api by click on 'Start API' button on below screenshot.

<img width="471" alt="capture" src="https://user-images.githubusercontent.com/21693119/36646793-053538d8-1a42-11e8-9da2-5b37363abd4a.PNG">

I tried to start through command prompt and not working still
 
![image](https://user-images.githubusercontent.com/21693119/36646838-962de6e6-1a42-11e8-8069-e8a18f718e8c.png)

**Comment by arkadiyala** [comment]
![image](https://user-images.githubusercontent.com/21693119/36646871-1cde16d4-1a43-11e8-932f-9c265697f686.png)

**Comment by codewatchorg** [comment]
Per the above screenshots, Python is either not installed on your machine or is not part of your path.  If you wanted to run from the command line, then you wouldn't do it from within Jython as the sqlmapapi.py script is included with sqlmap.  Jython is needed to run my tool from within Burp and has nothing to do with sqlmap.

**Comment by arkadiyala** [comment]
1.  I have installed jython(Standard, Not standalone) from below link.
http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar
2. Then Installed "SQLiPy Sqlmap Integration" from Burp Suite "BApp Store" tab.
3. Then setup C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WebEx\PTools020000000;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;**C:\jython2.7.0\bin**

4.  Click on Start API button(Please see below screenshot).
![image](https://user-images.githubusercontent.com/21693119/36694906-4db79236-1b05-11e8-831c-a002381411ac.png)

Do i need to Install Python separately?

**Comment by arkadiyala** [comment]
If I need to install Python separately , What version do i need to install?

**Comment by codewatchorg** [comment]
sqlmap is a Python based script, so yes, you need Python to be able to run it as well as the sqlmapapi.py script that comes with sqlmap.

As you can see in the screenshot above, my tool cannot find Python on your system.

I believe that sqlmap will only currently work with Python 2.x (you should install the latest version of 2.7).

**Comment by arkadiyala** [comment]
SQLmap API is running.
![image](https://user-images.githubusercontent.com/21693119/36701768-2ba8d3e8-1b1a-11e8-9a9e-f110b33ca85f.png)

However i did not see SQLiPy Scan. Please help me.
![image](https://user-images.githubusercontent.com/21693119/36701809-52f48118-1b1a-11e8-979f-d27e1103a59a.png)

**Comment by arkadiyala** [comment]
![image](https://user-images.githubusercontent.com/21693119/36702063-37f6d69e-1b1b-11e8-8806-a9333c3bfaea.png)

**Comment by codewatchorg** [comment]
SQLiPy is just an integration tool for Burp and sqlmap.  Your comments and screenshots indicate a lack of basic understanding of how those two tools work individually.  You need to learn how to use Burp and sqlmap by themselves first, I recommend buying a copy of the web application hackers handbook.

In the above screenshot, it shows that you started the sqlmapapi on 127.0.0.1:9090 but also have your Burp proxy set to 127.0.0.1:9090.  That won't work, they can't both listen on the same IP and port.

You are also right clicking in the wrong spot above for sending to SQLiPy.  You must click within the request tab, not from the "Contents" table.
