### ISSUE TITLE
always freezes the whole burp suite 

### ISSUE THREAD

**Issue by riteqylubu** [codewatchorg/sqlipy#21]

**Comment by codewatchorg** [comment]
Are you running it on Windows?  If so, are you starting sqlmapapi within the extension?

I have found that the sqlmapapi becomes unresponsive if started from a Windows command prompt or via the tool.  I have no idea why as it is not my code.  I found this out one time after it became unresponsive for me, then I submitted a request manually to the API and it never responded.  If you kill the Python processes for sqlmapapi Burp will respond again.

Try starting it either via Ubuntu Bash for Windows or in a Cygwin shell.  That is what I do on my Windows machines and it never becomes unresponsive.

**Comment by riteqylubu** [comment]
oh ok so it's not your code sorry 
you can contact stamparm or open an issue in his repository so he can figure it out

**Comment by codewatchorg** [comment]
I opened an issue.  I had been trying to figure out where in the API the problem was, as it didn't use to have a problem from the Windows command prompt, but I haven't had any success in tracking down the issue.

**Comment by riteqylubu** [comment]
Great Let's wait for stamparm response 
Good Luck

**Comment by riteqylubu** [comment]
running the api though powershell dosen't freeze it
tried with lastest sqlmap dev version
you can run it in a hidden ps window though the tool

**Comment by codewatchorg** [comment]
How are you running it with PowerShell?

**Comment by riteqylubu** [comment]
instead of starting from cmd start it from powershell windows

**Comment by codewatchorg** [comment]
So you launch a PowerShell console with: "powershell.exe" and then run "python sqlmapapi.py -s -H IP -p PORT" ?

Or are you starting it with PowerShell code?  Can you be more specific?

**Comment by riteqylubu** [comment]
exactly powershell.exe python sqlmapapi.py -s -H IP -p PORT
never ever freezes or becomes unresponsive

**Comment by codewatchorg** [comment]
Ok, so you are running the sqlmapapi directly from the command prompt using PowerShell, not starting it within a PowerShell console.

**Comment by codewatchorg** [comment]
I believe this is now resolved with https://github.com/codewatchorg/sqlipy/commit/56891294079de60c4d0824492b8bce9b1291607c

**Comment by riteqylubu** [comment]
Very Great to hear that no more freezes Good Luck
