### ISSUE TITLE
https://github.com/codewatchorg/sqlipy

### ISSUE THREAD

**Issue by Gargo** [codewatchorg/sqlipy#22]
```
SQLiPy relies on a running instance of the SQLMap API server. You can manually start the server with:
python sqlmapapi.py -s -H <ip> -p <port>
```
AND? There is no such file in this repo!

**Comment by codewatchorg** [comment]
The sqlmapapi.py file is part of sqlmap - it is included with sqlmap.  However, my extension now bundles sqlmap with it, so yes, there is in fact a sqlmapapi.py file included in the repo within the sqlmap.zip file.  I recommend installing the extension through the Burp BApp store though.

**Comment by Gargo** [comment]
@codewatchorg does it work with burp suite free? Or does it require pro version? I ask because I can't install it in pro - I get "installing" label infinitely.
And finally what about to fix readme because currently it is unclear how to use this repo?

**Comment by codewatchorg** [comment]
I'm not aware of anyone running into an issue installing it via the BApp store, and I would have no insight into that as the install process through the store is out of my control.  It works in both the pro version (there are more features as it logs issues to the Target issues tab) and the free version (it will save the results in an HTML file).

Can you be more specific on "fix readme"?  If installing through the repo (NOT RECOMMENDED), then you would install it like any other Python extension.  Download the repo to a folder, and add a Python extension, with the SQLiPy.py file as the extension.
