### ISSUE TITLE
No "SQLiPy Scan" option in context menu

### ISSUE THREAD

**Issue by sohelahmed786** [codewatchorg/sqlipy#25]
Hi codewatchorg, 
I've installed the plugin and installation went fine. There is a tab which shows sqlmap api, scanner, etc. But when i right-click on proxy tab url , the option to send to SQLiPy tab is missing. I'm using java version 8. Burp version - 2020.2
![burp-nosqli-in-menu](https://user-images.githubusercontent.com/12643717/92309958-4e55d600-efc7-11ea-84cb-f8e32dc57f68.png)

**Comment by codewatchorg** [comment]
You must click within the actual request window to send the request to SQLiPy.
