### ISSUE TITLE
No right click console integration

### ISSUE THREAD

**Issue by markisback** [codewatchorg/sqlipy#31]
I'm running burp 2021.5.2. Just added sqlipy sqlmap integration from the  BAapp store. The SQLipy tab appears, but not the right click integration. I've restarted burp, reinstalled the extension, but no go.

I'm running jython 2.7.2.

Any ideas?

**Comment by codewatchorg** [comment]
Recent versions of Burp changed where extension options show up. If you load the extension, you should be able to send it to SQLiPy by right clicking a request, and scroll down to "Extensions -> SQLiPy Scan."

**Comment by markisback** [comment]
Yeah you're right. I was expecting to be able to right click on a request in the proxy tab, but that extensions menu only shows when you're inside a request. my bad. thanks
