### ISSUE TITLE
Problem with running SQLiPy.py

### ISSUE THREAD

**Issue by amammad** [codewatchorg/sqlipy#32]
Hi dear.
I have some problems with running, here the picture :
![image](https://user-images.githubusercontent.com/77095239/127298334-a836ff25-ff85-4338-87ec-cc9b4db7244d.png)
and Really I going around for 2 hours and at the end I didn't able to solve this problem.
can you give me some help and tips ?
tanks so much my friend.

**Comment by codewatchorg** [comment]
Amammad, Burp extensions are loaded within Burp, please see Burp's documentation on how to load a Python extension.

**Comment by amammad** [comment]
Excuse me for taking your valuable time, I want to run the `sqlmapapi.py` but I do wrong and stupid thing.
