### ISSUE TITLE
"Start Scan" button does nothing

### ISSUE THREAD

**Issue by benjaminsec** [codewatchorg/sqlipy#34]
Trying with both local or remote api, the extension detects the API running, clicking on "Start Scan" literally does nothing
![sqlmapapi](https://user-images.githubusercontent.com/72479455/159818531-83548914-9ca0-42c7-af99-9b3f2d58d416.gif)
.

**Comment by codewatchorg** [comment]
Are you using the version of sqlmap bundled with the extension? Can you confirm the sqlmapapi was actually started? Can you provide logs from the "Extender" tab for the extension?

What version of Burp / sqlmap / SQLiPy / Java / Jython are you using? There are basically no details to help me troubleshoot here and no one else has ever reported this being an issue.

**Comment by codewatchorg** [comment]
No help/details received so closing.
