### ISSUE TITLE
Cannot See Scan Results

### ISSUE THREAD

**Issue by tylerOelking** [codewatchorg/sqlipy#36]
I was able to start a scan and got to this stage, however, I am not seeing any results for this scan. 

![Pasted Graphic](https://user-images.githubusercontent.com/107150270/195705248-16c22d59-3034-47f0-956f-113109072955.png)

As shown above, the scan gets to the "[15:29:47] [DEBUG] (ae8432fcc683d818) Retrieved scan data and error messages" step.

Here is the config of my scan. 
![Pasted Graphic 1](https://user-images.githubusercontent.com/107150270/195705552-c776faa6-ac3b-4c5b-93a8-afd8d4c8583d.png)

The sqlmap logs tab shows nothing.
![image](https://user-images.githubusercontent.com/107150270/195705618-c235b4b6-13b5-407f-9bd5-3b8b669a6802.png)

I am running python 2.7.18. 
I have jython 2.7 standalone jar installed.

**What should I be seeing if the tool is working as intended?** 

Any help would be greatly appreciated.

**Comment by codewatchorg** [comment]
The log will never show anything without hitting that ... button (I'm terrible at GUI development, for some reason it doesn't show on your screen but that button should say "Get". Did you click that button? If so, were there errors in the extender "Output" or "Errors" tabs for the extension?

**Comment by codewatchorg** [comment]
If there are any results (SQL injection identified) they will be reported as Issues in the Target tab. If nothing is found, the only results are in the logs.

**Comment by codewatchorg** [comment]
No more info provided to know if it was a bug in reporting in the Targets tab.
