### ISSUE TITLE
Sqlmaps do not keep path

### ISSUE THREAD

**Issue by kolor33** [codewatchorg/sqlipy#38]
Hi Team
I would like ask about sqlmap integrate with Burp.The issue is about keep setting by sqlmap .All time when I start Burp extension do not hold path for python.
I have to manual show path .It is any option to remember path for sqlmaps.

This is my path for python which should be keep by extension all time .??

![1](https://user-images.githubusercontent.com/32041737/197540617-177b77e1-1aef-4174-a465-12f99e804e5a.jpg)

**Comment by codewatchorg** [comment]
The extension does not currently support saving this data. If you have a typical Python install, the path is recorded in the registry, and the extension will automatically detect the path, but it looks like you installed in an untraditional way (not using a Python installer).

**Comment by codewatchorg** [comment]
Not planning to fix as the script auto-identifies paths in most cases.
