### ISSUE TITLE
SQLMap API is NOT running Error

### ISSUE THREAD

**Issue by Chris1871** [codewatchorg/sqlipy#39]
Preface - I tried following the troubleshooting steps in the other issue regarding the API not starting but it didn't solve it.

I'm on the latest version of Kali Linux VM using VirtualBox.  Latest version of BurpSuite Community Edition.
Jython version is jython-standalone-2.7.3.jar

When I try and start SQLMap API through burp it doesn't work, so I launch it through the CLI and (see screen shot below) it looks like it's run successfully but Burp still shows that the API is not running.

So far I've tried using python 3 and python 2, different ports and reinstalling burp all to no avail.

Greatly appreciate any help, thx.

Java Version:
![image](https://user-images.githubusercontent.com/101999480/203185465-8fe21e2f-ece8-4e01-a182-865107d3129a.png)

SQL Map API Successfully running in CLI:

![image](https://user-images.githubusercontent.com/101999480/203185348-d57355e1-b20f-4de7-b072-12020ab7e263.png)

BurpSuite UI:

![image](https://user-images.githubusercontent.com/101999480/203185827-2af6ac90-24f1-42d9-99be-31b8606df6ab.png)

**Comment by codewatchorg** [comment]
So if you manually start the API, the extension definitely WILL NOT show that it is running but it will WORK JUST FINE. You just have to manually set the scanner tab to point to the right IP and port.

I just downloaded the latest kali, did an apt update and apt upgrade, used the latest version of Burp and tracked this down.

This appears to be a bug in Jython 2.7.3 - I have been using 2.7.2. When I used the latest Jython (2.7.3) I had the same error but when I used 2.7.2 it worked.

**Comment by Chris1871** [comment]
Thanks for doing all of that troubleshooting.  I switched to jython 2.7.2 and still having the issues, this is the output I see.  There's nothing in the error logs or other logs from what I can tell, so just posting what I've found

I will try and get a fresh copy of kali and do all the steps you did but in the mean time maybe you see something from this output?

![image](https://user-images.githubusercontent.com/101999480/203391275-c1d59d7b-6551-4f40-9712-b9460cb3a8ec.png)

**Comment by codewatchorg** [comment]
Did you unload/reload the extension with Burp pointing to Jython 2.7.2? If not, I am unsure how to recreate since I just today installed and updated the latest version of Kali (Kali-rolling 2022.4), the latest version of Burp (2022.9.6), the version of the extension in the BApp store (0.8.2), same version of Python (2.7.18), and used Jython 2.7.2 (I'm using the standalone Jython JAR file).

I'm using Burp Pro, but that shouldn't matter since that only changes extension output, not task creation.

The only other difference is Java version. I didn't bother to figure out installing JDK 11, I just went with what Kali had, which is OpenJDK 17.0.5.

**Comment by codewatchorg** [comment]
Sounds like you got the API started with the extension, so this is a new problem? I don't see in the above where the API has been started, either way (if started manually) then this would be a whole separate problem.

If you go to the SQLiPy.py file for the extension and add "import traceback" underneath "import os" (around line #60), then add the following before the "print 'SQLMap task creation failed\n'" lines at #1560 and #1563:
print(traceback.format_exc())

It should give errors that will help resolve.

**Comment by Chris1871** [comment]
I just started with a fresh kali install, upgraded it etc just like you did earlier and now it's working.  Was able to get the UI to launch the API successfully, thanks for all your help!

![image](https://user-images.githubusercontent.com/101999480/203415944-3c384f9e-d046-43f3-b0ff-4d72520ab9b0.png)
