### ISSUE TITLE
Allow Specification of Technique in BurpSuite

### ISSUE THREAD

**Issue by NoPurposeInLife** [codewatchorg/sqlipy#40]
The App in BurpSuite does not have an option to specify technique thus requiring the user to manually copy and paste the sqlmap command into a terminal in order to specify the technique

**Comment by codewatchorg** [comment]
By default, sqlmap (and thus this extension) attempt all possible techniques. What are your use cases to specify a specific technique or a small combination of them versus just trying them all? If the use case makes sense, I will consider how best to support adding that as an option.

**Comment by NoPurposeInLife** [comment]
1. Time Saving (Since it doesnt need to try other techniques)
2. Most SQLi can be identified via Time Based Techniques (Boolean Based and Syntax Based only occurs if you get a dynamic response from the web page - But Time Based is more of a catch-all)

I think that's all, by allowing the us to specify the technique, it would then save me quite some time without copy pasting the command into a terminal, thanks!

**Comment by codewatchorg** [comment]
I can try to work this into the next update.

**Comment by codewatchorg** [comment]
Added
