### ISSUE TITLE
Critical Error When Trying to Run

### ISSUE THREAD

**Issue by tohitsugu** [codewatchorg/sqlipy#44]
Using  Jython Standalone 2.7.2 (not sure if that is relevant) and Python 3.12 I was unable to start the sqlmap API using the Burp panel. Instead, I downloaded sqlmap and manually started the sqlmapapi.py server. I connect to my manual API instance using the correct port and 127.0.0.1 

When attempting to **Start Scan** on any host, I receive the following error in the console window where the API is running: 

```
PS C:\Users\ianfr\sqlmap-1.7.12\sqlmap > python .\sqlmapapi.py -s -H 127.0.0.1 -p 9191
[08:37:55] [INFO] Running REST-JSON API server at '127.0.0.1:9191'..
[08:37:55] [INFO] Admin (secret) token: af51a5ad488cef25452f7917e160a097
[08:37:55] [DEBUG] IPC database: 'C:\Users\ianfr\AppData\Local\Temp\sqlmapipc-ezu6cbci'
[08:37:55] [DEBUG] REST-JSON API server connected to IPC database
[08:37:55] [DEBUG] Using adapter 'wsgiref' to run bottle
[08:38:16] [WARNING] [0] Invalid task ID provided to scan_status()
[08:38:53] [DEBUG] Created new task: '68247d953bd5bd53'
[08:38:53] [DEBUG] (68247d953bd5bd53) Requested to set options
[08:38:53] [DEBUG] (68247d953bd5bd53) Listed task options
[08:38:53] [DEBUG] (68247d953bd5bd53) Started scan
[08:38:54] [CRITICAL] you have provided an invalid and/or unreadable configuration file ('AttributeError: 'UnicodeRawConfigParser' object has no attribute 'readfp'')
```

**Comment by tohitsugu** [comment]
I am able to start the API inside burp when using the manually downloaded copy of sqlmapapi.py only - attempting to use the version in `C:\Users\ianfr\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\sqlmapapi.py` will not start but hangs with no message.

**Comment by codewatchorg** [comment]
There is nothing in the "Errors" or "Output" tabs when you go to "Extensions"->"SQLiPy Sqlmap Integration"? What version of the extension are you using?

I cannot recreate your error when running manually. I just downloaded version 1.7.12-6 and it worked fine.
![sqlmap-github-test](https://github.com/codewatchorg/sqlipy/assets/7938289/351aecba-aebf-47d4-a789-5d079184dd9e)

**Comment by codewatchorg** [comment]
What options are you setting when you run a scan? Maybe one of those options is broken.

**Comment by tohitsugu** [comment]
I ran it with level 3, risk 2. Left everything as default.  Note that I can't actually start the API using the `sqlmapapi.py` at `C:\Users\ianfr\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\sqlmapapi.py` -- it just hangs and it says "SQLMap API is NOT Running!" 

When I tell it to use the `sqlmapapi.py` I downloaded manually, it runs - but with errors. 

Here is the output from the installed extensions menu "Output" tab: 

```
SQLiPy - 0.8.5
Burp interface to SQLMap via the SQLMap API
josh.berry@codewatch.org


Could not find python path in registry at: HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7\InstallPath.

Could not find python path in registry at: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\2.7\InstallPath.

Could not find python path in registry at: HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.x\InstallPath\ExecutablePath.

Could not find python path in registry at: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\3.x\InstallPath\ExecutablePath.

Python found in system path at: C:\Python312\python.exe

SQLMap API found at: C:\Users\ianfr\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\sqlmapapi.py

Calling: C:\Python312\python.exe C:\Users\ianfr\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\sqlmapapi.py -s -H 127.0.0.1 -p 9090

Failed to start the SQLMap API

raceback (most recent call last):
 File "C:\Users\ianfr\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\lib\utils\api.py", line 58, in <module>
```

Here is the "Errors" tab output: 

```
Traceback (most recent call last):
  File "C:\Users\ianfr\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\SQLiPy.py", line 1295, in getLogs
    print 'Failed to get logs for: '+self._jComboLogs.getSelectedItem().split('-')[0]+'\n'
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by tohitsugu** [comment]
Tried reinstalling the extension, now it fails with a different error: 

```

Selected Python at C:\Python312\python.exe
Calling: C:\Python312\python.exe C:\Users\ianfr\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\sqlmapapi.py -s -H 127.0.0.1 -p 9091

Failed to start the SQLMap API

raceback (most recent call last):
   import base64, calendar, cgi, email.utils, functools, hmac, imp, itertools,\
```

Maybe it's my version of python?

**Comment by codewatchorg** [comment]
Yeah, that is my initial assumption, as that looks like sqlmapapi itself is failing for some reason, which is out of my control.

**Comment by tohitsugu** [comment]
I'm trying to figure out a workaround for this. Installing a different version of Python also fails. If I start the API manually from the command-line with the `sqlmapapi.py`  installed using `pip`, and then click "Start API", it changes to "SQLMap API IS CURRENTLY RUNNING!" 

The output from the `SQLiPy -> SQLMap Logs` tab shows: 

```
Log results for: sqlmap.py -u "https:/site.com:443/something?id=1
...
INFO: 12:32:00 - testing connection to the target URL
```

No further output is shown. 

If I switch to the `Extensions -> Installed -> SQLiPy Sqlmap Integration -> Output` I see the following: 

```
Started SQLMap Scan on Task 5973b5f57eb0bc6a with Engine ID: 29584 - https://site.com:443/something?id=1

Checking results on task: 5973b5f57eb0bc6a

Scan for task 5973b5f57eb0bc6a is still running.

Scan for task 55ca8c5b141bd6a8 is still running.

Scan for task 5973b5f57eb0bc6a is still running.

Scan for task 55ca8c5b141bd6a8 completed.  Gathering results.

Scan completed for task 55ca8c5b141bd6a8 but SQLi vulnerabilities were not found.
```

Does this look correct? Or should there be more details beyond the `INFO: 12:32:00 - testing connection to the target URL`  line from the  `SQLiPy -> SQLMap Logs` tab? If this looks correct then I can use this method as a workaround - though I feel like perhaps there is some missing information from the Logs/output.

**Comment by codewatchorg** [comment]
That all looks like correct output from the Output section, it performed and completed the scan according to that data.
