### ISSUE TITLE
Stuck with "Start API" button

### ISSUE THREAD

**Issue by matt-elson** [codewatchorg/sqlipy#5]
After setting IP/Port in SQLMap API tab and clicking "Start API", but nothing happens.

![2015-4-22 16-46-04](https://cloud.githubusercontent.com/assets/2929106/7270500/277e13d6-e90f-11e4-863d-d00be416aa84.png)

**Comment by codewatchorg** [comment]
How do you mean?  If you run netstat, is Python listening on TCP port 9090?  It should start the API as a process, you won't actually see anything happen.  Once the API is up and running, you can send requests to it.

NOTE: This is not the preferred method of running the API.  When Java spawns a process, it doesn't capture the correct PID, and therefore you have to manually kill the process.  Plus, you don't see any output from the sqlmapapi itself.  I recommend running manually:
python sqlmapapi.py -s -H 192.168.1.5 -p 9090, then on the "Sqlmap Scanner" tab, manually input the IP and Port information.

**Comment by yashar6909** [comment]
I had the same issue,
How I got around it was to git clone the sqlmap (fresh from github)
I found that localhost (127.0.0.1) worked perfectly in the way that codewatchorg has said
./sqlmapapi.py -s -H 127.0.0.1 -p 9090 and then add those details in the SQLMap scanner tab,
just ignore the first tab (SQLMap API) and you will see a verbose version of what sqlmapapi is doing in the background.
Hope it helps

**Comment by codewatchorg** [comment]
Ok, this seems to have only affected *nix variants.  I have made an update that works on my Linux distro, so I think this problem has been corrected.  However, I still recommend starting the API separately.

**Comment by codewatchorg** [comment]
I'm going to close this as I believe it is resolved now.
