### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by Hipapheralkus** [codewatchorg/sqlipy#6]
I'm, wondering if it would be possible to incorporate a Burp session management functionality. When I perform tests, I'm kicked out of the session by WAF. Since Burp already contains session management and is able to create a session again; would it be feasible to use this as well?
Thanks for this great tool:)

**Comment by codewatchorg** [comment]
That is really outside the scope of the tool as it is just integration between Burp and Sqlmap.  The best way to do this is to configure sqlmap (through sqlipy) to proxy connections through Burp.  Then Burp will handle the sqlmap session.

**Comment by Hipapheralkus** [comment]
That's great idea and it is working:) I just had to turn on "Proxy" in scope of Burp's session detection; and set proxy in SQLMapper to http://127.0.0.1:8081 and now it is working:) Thank you for advice:)
