### ISSUE TITLE
tor

### ISSUE THREAD

**Issue by txt3rob** [codewatchorg/sqlipy#7]
Hi,

Is it possible to add a tor option to the scanner at all?

the latest sqlmap has an option for it and could not see an option for  socks proxy on the addon.

**Comment by codewatchorg** [comment]
There is a proxy option at the bottom of the tool.  I guess you could probably use the plugin to proxy through Burp, and then chain Burp through a Tor proxy.  That is ugly but probably the only way to do it at this time.

I will look into specifically adding the tor features from sqlmap.

**Comment by codewatchorg** [comment]
I added tor support with the last commit: https://github.com/codewatchorg/sqlipy/commit/638218937416fa6345cdc1b4b173a82604ab1f6a
