### ISSUE TITLE
Scan screen bounds hide "Start Scan" button

### ISSUE THREAD

**Issue by phillycheeze** [codewatchorg/sqlipy#8]
Using an environment with a small window, the "Start Scan" button is hidden.

The scrollbar in burp goes until the "Tamper Scripts" input but stops at that. The button is effectively below the viewport of burp. 

I expect the problem lies in these two lines:
`self._jButtonStartScan.setBounds(346, 1047, 103, 29)`
`self._jScanPanel.setPreferredSize(awt.Dimension(1010,1010))`

**Comment by codewatchorg** [comment]
Resolved with merge of pull request: https://github.com/codewatchorg/sqlipy/pull/9/commits/647073b0d07f773e34f3289e73c6f14da2746e8a
